//! Device catalog: hardware models from the built-in catalog, which is embedded in the
//! program, and from the user's catalog directories.

mod face;
mod legend;
mod model;
mod numbering;

use std::borrow::Cow;
use std::collections::BTreeMap;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use miette::SourceSpan;
use thiserror::Error;

pub use face::{Cell, Element, Face, FaceKind, Faces, STRIP_WIDTH};
pub use legend::{
    Align, Direction, Legend, LegendEntry, Media, Numbering, Order, Part, PartKind, State,
};
pub use model::{Components, Depth, Ears, Kind, Model, Mount};
pub use numbering::{Numbers, Slot};

use crate::kdl_reader::{FileError, Problem};
use crate::{IDENTIFIER_RULE, is_identifier};

/// The device catalog: every hardware model available to the racks.
///
/// Opening a catalog only lists the model files. A model is read the first time it is
/// requested through [`Catalog::model`] and kept for later requests, so each file is parsed
/// at most once and files that are never used are never parsed.
#[derive(Debug, Default)]
pub struct Catalog {
    entries: BTreeMap<String, Entry>,
}

/// The model files of the built-in catalog: each file's path relative to the repository's
/// `catalog/` folder, with `/` separators, and its contents. Generated by `build.rs`.
const BUILTIN: &[(&str, &str)] = include!(concat!(env!("OUT_DIR"), "/builtin_catalog.rs"));

/// Where a model comes from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Origin {
    /// The built-in catalog, embedded in the program.
    BuiltIn,
    /// A catalog directory, such as `~/.config/rackctl/catalog`.
    User,
}

/// One model file and, once it has been requested, the result of reading it.
#[derive(Debug)]
struct Entry {
    origin: Origin,
    source: Source,
    model: OnceLock<Result<Model, FileError>>,
}

/// Where the text of a model file is found.
#[derive(Debug)]
enum Source {
    /// Embedded in the program, with the file's path relative to the catalog folder.
    Embedded { path: &'static str, text: &'static str },
    /// A file on disk.
    File(PathBuf),
}

impl Source {
    /// Returns the name used for the file in error messages.
    fn name(&self) -> String {
        match self {
            Self::Embedded { path, .. } => format!("catalog/{path}"),
            Self::File(path) => path.display().to_string(),
        }
    }
}

/// The reason a model could not be provided.
#[derive(Debug, Error)]
pub enum ModelError<'a> {
    /// The catalog has no model with the requested identifier.
    #[error("unknown model `{id}`")]
    Unknown {
        /// The identifier that was requested.
        id: String,
    },
    /// The model's file exists but contains problems.
    #[error(transparent)]
    Invalid(&'a FileError),
}

impl Catalog {
    /// Returns the built-in catalog, which is embedded in the program.
    #[must_use]
    pub fn builtin() -> Self {
        let mut catalog = Self::default();
        for &(path, text) in BUILTIN {
            if is_model_file(Path::new(path)) {
                let id = model_id(Path::new(""), Path::new(path));
                catalog.insert(id, Origin::BuiltIn, Source::Embedded { path, text });
            }
        }
        catalog
    }

    /// Opens a catalog made of the model files found in `dirs` and their subdirectories,
    /// without the built-in models. See [`Catalog::add_dirs`].
    ///
    /// # Errors
    ///
    /// Returns an error if a directory exists but cannot be read.
    pub fn open(dirs: &[impl AsRef<Path>]) -> io::Result<Self> {
        let mut catalog = Self::default();
        catalog.add_dirs(dirs)?;
        Ok(catalog)
    }

    /// Adds the model files found in `dirs` and their subdirectories.
    ///
    /// Directories are searched in order. A model replaces any model already in the catalog
    /// with the same identifier, so a user's catalog can override the built-in catalog.
    /// Directories that do not exist are skipped.
    ///
    /// # Errors
    ///
    /// Returns an error if a directory exists but cannot be read.
    pub fn add_dirs(&mut self, dirs: &[impl AsRef<Path>]) -> io::Result<()> {
        for dir in dirs {
            let dir = dir.as_ref();
            match self.add_dir(dir, dir) {
                Err(error) if error.kind() == io::ErrorKind::NotFound => {}
                result => result?,
            }
        }
        Ok(())
    }

    /// Returns the identifiers of all models in the catalog, in alphabetical order.
    pub fn ids(&self) -> impl Iterator<Item = &str> {
        self.entries.keys().map(String::as_str)
    }

    /// Returns where the model `id` comes from, or `None` if the catalog has no such model.
    #[must_use]
    pub fn origin(&self, id: &str) -> Option<Origin> {
        self.entries.get(id).map(|entry| entry.origin)
    }

    /// Returns the model `id`, reading its file the first time it is requested.
    ///
    /// # Errors
    ///
    /// Returns [`ModelError::Unknown`] if the catalog has no such model, and
    /// [`ModelError::Invalid`] if the model's file contains problems.
    pub fn model(&self, id: &str) -> Result<&Model, ModelError<'_>> {
        let Some(entry) = self.entries.get(id) else {
            return Err(ModelError::Unknown { id: id.to_owned() });
        };
        entry.model.get_or_init(|| load(id, &entry.source)).as_ref().map_err(ModelError::Invalid)
    }

    /// Reads every model and returns the problems of the invalid ones.
    #[must_use]
    pub fn invalid_models(&self) -> Vec<&FileError> {
        self.ids()
            .filter_map(|id| match self.model(id) {
                Err(ModelError::Invalid(error)) => Some(error),
                _ => None,
            })
            .collect()
    }

    /// Adds a model, replacing any model with the same identifier. A model whose identifier
    /// is invalid is recorded with the problem, so that it is reported when requested.
    fn insert(&mut self, id: String, origin: Origin, source: Source) {
        let model = if is_valid_id(&id) {
            OnceLock::new()
        } else {
            OnceLock::from(Err(invalid_name(source.name())))
        };
        self.entries.insert(id, Entry { origin, source, model });
    }

    /// Adds the model files in `dir` and its subdirectories, naming them relative to `root`.
    ///
    /// Hidden entries, whose names start with `.`, are skipped. Symbolic links to
    /// directories are not followed, so a link cannot make the search loop.
    fn add_dir(&mut self, root: &Path, dir: &Path) -> io::Result<()> {
        let mut entries = Vec::new();
        for entry in fs::read_dir(dir)? {
            let entry = entry?;
            entries.push((entry.path(), entry.file_type()?));
        }
        entries.sort_by(|(a, _), (b, _)| a.cmp(b));
        for (path, file_type) in entries {
            if is_hidden(&path) {
                continue;
            }
            if file_type.is_dir() {
                self.add_dir(root, &path)?;
            } else if is_model_file(&path) {
                self.insert(model_id(root, &path), Origin::User, Source::File(path));
            }
        }
        Ok(())
    }
}

/// Returns whether the file or directory is hidden: its name starts with `.`, like the lock
/// files some editors create next to the file being edited.
fn is_hidden(path: &Path) -> bool {
    path.file_name().is_some_and(|name| name.to_string_lossy().starts_with('.'))
}

/// Model files end in `.kdl`. Files starting with `_` hold shared parts of other models
/// and are not models themselves.
fn is_model_file(path: &Path) -> bool {
    let name = path.file_name().map(|name| name.to_string_lossy()).unwrap_or_default();
    path.extension().is_some_and(|extension| extension == "kdl") && !name.starts_with('_')
}

/// Derives a model identifier from its path, for example `dell/r630-sff8` from
/// `<root>/dell/r630-sff8.kdl`. Components are always joined with `/`.
fn model_id(root: &Path, path: &Path) -> String {
    let relative = path.strip_prefix(root).unwrap_or(path).with_extension("");
    relative
        .components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

/// A model identifier is valid when every part is a valid identifier.
fn is_valid_id(id: &str) -> bool {
    id.split('/').all(is_identifier)
}

fn invalid_name(name: String) -> FileError {
    let problem =
        Problem::new(format!("model file names {IDENTIFIER_RULE}"), SourceSpan::from(0..0))
            .with_help("rename the file, for example `dell/r630-sff8.kdl`");
    FileError::new(name, "", vec![problem])
}

/// Reads and parses one model file.
fn load(id: &str, source: &Source) -> Result<Model, FileError> {
    let name = source.name();
    let text = match source {
        Source::Embedded { text, .. } => Cow::Borrowed(*text),
        Source::File(path) => Cow::Owned(
            fs::read_to_string(path).map_err(|error| FileError::unreadable(&name, &error))?,
        ),
    };
    Model::parse(id, &text).map_err(|problems| FileError::new(name, text, problems))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testing::dir_with;

    const R630: &str = r#"model { name "Dell PowerEdge R630"; short "R630"; kind "server" }"#;

    #[test]
    fn lists_models_and_loads_them_on_request() {
        let dir = dir_with(&[("dell/r630-sff8.kdl", R630), ("cisco/sg300-28.kdl", "broken {")]);
        let catalog = Catalog::open(&[dir.path()]).expect("readable directory");

        assert_eq!(catalog.ids().collect::<Vec<_>>(), ["cisco/sg300-28", "dell/r630-sff8"]);
        assert_eq!(catalog.model("dell/r630-sff8").expect("valid model").short, "R630");
        assert!(matches!(catalog.model("cisco/sg300-28"), Err(ModelError::Invalid(_))));
    }

    #[test]
    fn returns_the_same_model_on_every_request() {
        let dir = dir_with(&[("dell/r630-sff8.kdl", R630)]);
        let catalog = Catalog::open(&[dir.path()]).expect("readable directory");

        let first = catalog.model("dell/r630-sff8").expect("valid model");
        let second = catalog.model("dell/r630-sff8").expect("valid model");
        assert!(std::ptr::eq(first, second));
    }

    #[test]
    fn embeds_the_built_in_catalog() {
        let catalog = Catalog::builtin();
        assert_eq!(catalog.origin("dell/r630-sff8"), Some(Origin::BuiltIn));
        assert_eq!(catalog.model("dell/r630-sff8").expect("valid model").short, "R630");
    }

    #[test]
    fn lets_a_user_model_replace_a_built_in_one() {
        let user =
            dir_with(&[("dell/r630-sff8.kdl", r#"model { name "My R630"; kind "server" }"#)]);
        let mut catalog = Catalog::builtin();
        catalog.add_dirs(&[user.path()]).expect("readable directory");

        assert_eq!(catalog.origin("dell/r630-sff8"), Some(Origin::User));
        assert_eq!(catalog.origin("dell/r730-sff8"), Some(Origin::BuiltIn));
        assert_eq!(catalog.model("dell/r630-sff8").expect("valid model").name, "My R630");
    }

    #[test]
    fn lets_a_later_directory_replace_a_model() {
        let builtin = dir_with(&[("dell/r630-sff8.kdl", R630)]);
        let user =
            dir_with(&[("dell/r630-sff8.kdl", r#"model { name "My R630"; kind "server" }"#)]);
        let catalog = Catalog::open(&[builtin.path(), user.path()]).expect("readable directories");

        assert_eq!(catalog.model("dell/r630-sff8").expect("valid model").name, "My R630");
    }

    #[test]
    fn skips_shared_parts_other_files_and_missing_directories() {
        let dir = dir_with(&[
            ("dell/r630-sff8.kdl", R630),
            ("dell/_poweredge-13g.kdl", "anything"),
            ("README.md", "notes"),
        ]);
        let missing = dir.path().join("missing");
        let catalog = Catalog::open(&[dir.path(), &missing]).expect("readable directory");

        assert_eq!(catalog.ids().collect::<Vec<_>>(), ["dell/r630-sff8"]);
    }

    #[test]
    fn skips_hidden_files_and_directories() {
        let dir = dir_with(&[
            ("dell/r630-sff8.kdl", R630),
            ("dell/.#r630-sff8.kdl", "editor lock file"),
            (".git/models.kdl", "anything"),
        ]);
        let catalog = Catalog::open(&[dir.path()]).expect("readable directory");

        assert_eq!(catalog.ids().collect::<Vec<_>>(), ["dell/r630-sff8"]);
    }

    #[cfg(unix)]
    #[test]
    fn does_not_follow_links_to_directories() {
        let dir = dir_with(&[("dell/r630-sff8.kdl", R630)]);
        std::os::unix::fs::symlink(dir.path(), dir.path().join("dell/loop")).expect("symlink");
        let catalog = Catalog::open(&[dir.path()]).expect("readable directory");

        assert_eq!(catalog.ids().collect::<Vec<_>>(), ["dell/r630-sff8"]);
    }

    #[test]
    fn reports_an_unknown_model() {
        let dir = dir_with(&[("dell/r630-sff8.kdl", R630)]);
        let catalog = Catalog::open(&[dir.path()]).expect("readable directory");

        match catalog.model("dell/r630-sf8") {
            Err(ModelError::Unknown { id }) => assert_eq!(id, "dell/r630-sf8"),
            other => panic!("expected an unknown model, got {other:?}"),
        }
    }

    #[test]
    fn reports_invalid_file_names() {
        let dir = dir_with(&[("Dell/R630.kdl", R630)]);
        let catalog = Catalog::open(&[dir.path()]).expect("readable directory");

        let Err(ModelError::Invalid(error)) = catalog.model("Dell/R630") else {
            panic!("expected an invalid model");
        };
        assert_eq!(error.problems()[0].message(), format!("model file names {IDENTIFIER_RULE}"));
        assert!(catalog.ids().eq(["Dell/R630"]));

        let dir = dir_with(&[("dell/r630-.kdl", R630)]);
        let catalog = Catalog::open(&[dir.path()]).expect("readable directory");
        assert!(matches!(catalog.model("dell/r630-"), Err(ModelError::Invalid(_))));
    }
}
